Fixing failed action

diff --git a/meta-git b/meta-git
--- a/meta-git
+++ b/meta-git
@@ -87,7 +87,7 @@ elif [ ! -z "$(typeset -f _core_"${ACTION}")" ]; then
 elif [ -x "${ABSOLUTE_PATH}/external/${ACTION}" ];then
   "${ABSOLUTE_PATH}/external/${ACTION}" "$@"
 else
-  >&2 echo "[ERROR] unknown action ${1:-'None entered'}"
+  >&2 echo "[ERROR] unknown action ${ACTION:-'None entered'}"
   >&2 echo "[ERROR] Please see $(basename "${0}") -h"
   exit 1
 fi
