Having a working solution for npm i in a meta repo

diff --git a/external/node-install b/external/node-install
--- a/external/node-install
+++ b/external/node-install
@@ -1,11 +1,31 @@
 #! /bin/sh
+set -eu
+PROJECTS=$(git submodule foreach --quiet '[ -f package.json ] && basename $(pwd) || true')
+
+_clean_up() {
+    >&2 echo "[INFO] Resetting modified package.json"
+    git submodule foreach --quiet '[ -f "package.json.bak" ] && mv package.json.bak package.json || true'
+}
+
+# Make sure we always clean up after ourselves
+trap '_clean_up' EXIT
+
 
 if [ -z "$(which lerna 2>/dev/null)" ];then
   >&2 echo "[ERROR] $(basename "$0") requires lerna to be installed"
 fi
 
+>&2 echo "[INFO] Linking Projects locally"
+# Create a backup file
+git submodule foreach --quiet '[ -f "package.json" ] && cp package.json package.json.bak || true'
+# Modifing the package json
+for project in ${PROJECTS}; do
+    for replace in ${PROJECTS};do
+        sed -i -e 's/git+ssh:\/\/git@github.com:SeedJobs\/'${replace}'.git/file:..\/'${replace}'/g' ${project}/package.json
+    done
+done
+>&2 echo "[INFO] Running npm install"
 npm i
-# Going through each directory and bootstraping any lerna projects
-# to ensure that we don't try search for node modules that don't exist
-# on the remote.
+
+>&2 echo "[INFO] Bootstraping any lerna projects"
 git submodule foreach --quiet '[ -f "lerna.json" ] && lerna bootstrap || true'
